# server配置
server:
  port: 8082
  # 线程池配置
  undertow:
    threads:
      worker: 10
      io: 10
    direct-buffers: true

jwt:
  # 密钥
  secret: qazwsxedcrfv
  # 过期时间(单位毫秒:12小时)
  expire: 43200000
# spring配置
spring:
  # 调整上传文件大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  # 数据库配置
  datasource:
    # 数据库驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接URL
    url: jdbc:mysql://localhost:3306/big_event?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    # 数据库用户名
    username: alleyf
    # 数据库密码
    password: 123456
  #  redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      timeout: 3000



# mybatis配置
mybatis:
  configuration:
    #  开启驼峰命名与下划线命名的自动转换
    map-underscore-to-camel-case: true
    # 日志实现类
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# logging配置
logging:
  level:
    # 日志级别为debug的sql
    sql: debug
# 本地文件上传配置
files:
  upload:
    path: E:\IDEAProjects\big_event\src\main\resources\static\files\

# 对象存储配置
qiniu:
  accessKey: xxx
  secretKey: xxx
  bucket: xxx
  domain: xxx
